# update global options
set global autoreload 'ask'
set global makecmd 'make -j8'
set global grepcmd 'ag --column'
set global ui_options ncurses_status_on_top=yes:ncurses_assistant=cat

# global key mappings
map global normal '#' ':comment-line<ret>'
map global normal '0' 'gh'
map global normal '$' 'gl'
map global -docstring 'search in files' user g ':grep'
map global -docstring 'next match' user n ':grep-next<ret>'
map global -docstring 'previous match' user p ':grep-prev<ret>'
map global -docstring 'copy to system clipboard' user y '<a-|>pbcopy<ret>; :echo -color Information "copied"<ret>'

# global hooks
hook global WinCreate .* %{
  # add global highlighters
  add-highlighter	number_lines -relative -hlcursor
}

